### ISSUE TITLE
Suggestion: adding a license 

### ISSUE THREAD

**Issue by nate-tsai** [smacker/newrelic-context#3]
HI @smacker 

I came across your repo and found it has great support for using Newrelic with Gorm. Do you plan to open source it by [adding a proper license](https://help.github.com/articles/licensing-a-repository/)? It'd be very nice if you could add a license so that others can use it.

Thank you!

**Comment by smacker** [comment]
Hi @Jeweller-Tsai 

I have just added MIT license to this repository.

**Comment by nate-tsai** [comment]
THANK YOU @smacker 👍
